module.exports = {
    https_prv: "../credential/temp.key",
    https_cert: "../credential/temp.crt",
    client_path: "../client/build",
    gppc_repo_prefix:"",
    repo_ssh_base: "git@github.com:MAPF-COMPETITION-REPOS",
    repo_web_base:"https://github.com/MAPF-COMPETITION-REPOS",
    external_resource:"https://raw.githubusercontent.com/MAPF-Competition/web_resource/develop",
    mongoose_string: "mongodb://127.0.0.1:27017/test_db?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0",
    sslCA_path: "../credential/rds-combined-ca-bundle.pem",
    github_org_link:"https://github.com/MAPF-COMPETITION-REPOS",
    github_api:"https://api.github.com",
    github_org:"MAPF-COMPETITION-REPOS", 
    github_state:"gppc_2021",
    GITHUB_CLIENT_ID:"Iv1.d2a1d674b2524202",
    GITHUB_APP_ID:"308423",
    GITHUB_REDIRECT_URI:"http://localhost:3000/github-login",
    GITHUB_SECRET_PATH:"../credential/MAPF_APP_LOCALHOST_SECRET",
    GITHUB_APP_KEY:"../credential/mapf-competiton-bot-test.2023-03-22.private-key.pem",
    GITHUB_INSTALLATION_ID: 35522712,
    start_kit_classic:"Start-Kit",
    start_kit_owner:"MAPF-Competition",
    storage_root:"storage/",
    storage_limit: 1024 * 1024 * 1024 * 10, // 10 Gb
    log_storage_root:"log_storage/",
    aws_accessKeyId:"AKIAZF47OJ234G3PJ4U5",
    aws_secretAccessKey: "../credential/aws-key",
    aws_region:"ap-southeast-2",
    aws_bucket:"mapf-participants-data",
    aws_account_id:"631157706423"
  };